"use client";

import type { ReactNode } from "react";
import { useMemo, useState } from "react";
import { AlertTriangle, Check, Grid2X2, ImageOff, Package, Pencil, Plus, Power, Save, Search, X } from "lucide-react";
import { useAuth } from "@/providers/auth-provider";
import { permissions } from "@/lib/permissions";
import { useCategories, useCreateProduct, useProducts, useSuppliers, useToggleProductActive, useUpdateProduct } from "@/hooks/use-catalog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Modal } from "@/components/ui/modal";
import { ActiveBadge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { TableSkeleton } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/ui/empty-state";
import { ErrorState } from "@/components/ui/error-state";
import { PriceComparison } from "@/components/catalog/price-comparison";
import type { Product } from "@/types";

interface ProductFormState { supplier_id: string; name: string; sku: string; description: string; current_price: string; currency: string; image_url: string; barcode: string; category: string; unit: string; units_per_carton: string; supplier_sku: string; current_stock: string; min_stock: string; recommended_stock: string; }
type ViewMode = "list" | "grid";
type StatusFilter = "all" | "active" | "inactive";
type StockFilter = "all" | "low" | "healthy" | "missing";
type InlineField = "name" | "sku" | "barcode" | "category" | "current_price" | "current_stock";
const EMPTY_FORM: ProductFormState = { supplier_id: "", name: "", sku: "", description: "", current_price: "", currency: "ILS", image_url: "", barcode: "", category: "", unit: "", units_per_carton: "", supplier_sku: "", current_stock: "", min_stock: "", recommended_stock: "" };
function parseOptionalInt(value: string): number | undefined { if (!value.trim()) return undefined; const n = Number(value); return Number.isFinite(n) ? Math.trunc(n) : undefined; }
function stockPercent(product: Product): number | null { if (product.current_stock == null || product.min_stock == null) return null; const target = product.recommended_stock ?? product.min_stock; if (target <= 0) return 100; return Math.max(0, Math.min(100, (product.current_stock / target) * 100)); }
function stockTone(product: Product): "neutral" | "danger" | "warning" | "healthy" { if (product.current_stock == null || product.min_stock == null) return "neutral"; if (product.current_stock < product.min_stock) return "danger"; if (product.recommended_stock != null && product.current_stock < product.recommended_stock) return "warning"; return "healthy"; }

function TableFilterInput({ value, onChange, placeholder, type = "text", className = "" }: { value: string; onChange: (value: string) => void; placeholder: string; type?: "text" | "number"; className?: string }) {
  return <div className="relative"><Search className="pointer-events-none absolute right-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400" /><Input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} aria-label={placeholder} type={type} min={type === "number" ? 0 : undefined} step={type === "number" ? "0.01" : undefined} className={`h-8 min-w-[100px] pr-7 text-xs ${className}`} /></div>;
}

function TableFilterSelect<T extends string>({ value, onChange, children, className = "" }: { value: T; onChange: React.Dispatch<React.SetStateAction<T>>; children: React.ReactNode; className?: string }) {
  return <Select value={value} onChange={(e) => onChange(e.target.value as T)} className={`h-8 min-w-[110px] text-xs ${className}`}>{children}</Select>;
}

export default function CatalogPage() {
  const { user } = useAuth();
  const canManage = permissions.canManageCatalog(user);
  const [skuFilter, setSkuFilter] = useState(""); const [nameFilter, setNameFilter] = useState(""); const [supplierFilter, setSupplierFilter] = useState("all"); const [statusFilter, setStatusFilter] = useState<StatusFilter>("all"); const [categoryFilter, setCategoryFilter] = useState("all"); const [stockFilter, setStockFilter] = useState<StockFilter>("all"); const [priceMin, setPriceMin] = useState(""); const [priceMax, setPriceMax] = useState(""); const [viewMode, setViewMode] = useState<ViewMode>("list"); const [modalOpen, setModalOpen] = useState(false); const [showMoreFields, setShowMoreFields] = useState(false); const [editingProduct, setEditingProduct] = useState<Product | null>(null); const [form, setForm] = useState<ProductFormState>({ ...EMPTY_FORM }); const [formError, setFormError] = useState<string | null>(null); const [inlineEdit, setInlineEdit] = useState<{ id: number; field: InlineField; value: string } | null>(null);
  const { data: products, isLoading, isError, refetch } = useProducts(); const { data: suppliers } = useSuppliers(); const { data: categoryOptions = [] } = useCategories(); const createProduct = useCreateProduct(); const updateProduct = useUpdateProduct(inlineEdit?.id ?? editingProduct?.id ?? -1); const toggleActive = useToggleProductActive();
  const supplierName = (supplierId: number) => suppliers?.find((s) => s.id === supplierId)?.name ?? `#${supplierId}`;
  const categories = useMemo(() => Array.from(new Set([...(categoryOptions ?? []), ...(products ?? []).map((p) => p.category).filter(Boolean) as string[]])).sort((a, b) => a.localeCompare(b, "he")), [categoryOptions, products]);
  const filtered = useMemo(() => { if (!products) return []; const min = priceMin.trim() ? Number(priceMin) : null; const max = priceMax.trim() ? Number(priceMax) : null; return products.filter((p) => { const matchesSku = !skuFilter.trim() || (p.sku ?? "").toLowerCase().includes(skuFilter.trim().toLowerCase()); const matchesName = !nameFilter.trim() || p.name.toLowerCase().includes(nameFilter.trim().toLowerCase()); const matchesSupplier = supplierFilter === "all" || String(p.supplier_id) === supplierFilter; const matchesStatus = statusFilter === "all" || (statusFilter === "active" ? p.active : !p.active); const matchesCategory = categoryFilter === "all" || p.category === categoryFilter; const matchesStock = stockFilter === "all" || (stockFilter === "low" ? p.current_stock != null && p.min_stock != null && p.current_stock < p.min_stock : stockFilter === "healthy" ? p.current_stock != null && p.min_stock != null && p.current_stock >= p.min_stock : p.current_stock == null || p.min_stock == null); const matchesMin = min == null || (Number.isFinite(min) && p.current_price >= min); const matchesMax = max == null || (Number.isFinite(max) && p.current_price <= max); return matchesSku && matchesName && matchesSupplier && matchesStatus && matchesCategory && matchesStock && matchesMin && matchesMax; }); }, [products, skuFilter, nameFilter, supplierFilter, statusFilter, categoryFilter, stockFilter, priceMin, priceMax]);
  const activeFilters = [skuFilter, nameFilter, supplierFilter, statusFilter, categoryFilter, stockFilter, priceMin, priceMax].filter((value) => value && value !== "all").length;
  const clearFilters = () => { setSkuFilter(""); setNameFilter(""); setSupplierFilter("all"); setStatusFilter("all"); setCategoryFilter("all"); setStockFilter("all"); setPriceMin(""); setPriceMax(""); };
  const metrics = useMemo(() => { const list = products ?? []; return { total: list.length, active: list.filter((p) => p.active).length, low: list.filter((p) => p.current_stock != null && p.min_stock != null && p.current_stock < p.min_stock).length, categories: new Set(list.map((p) => p.category).filter(Boolean)).size }; }, [products]);
  const isLowStock = (p: Product) => p.current_stock != null && p.min_stock != null && p.current_stock < p.min_stock;
  const openCreateModal = () => { setEditingProduct(null); setForm({ ...EMPTY_FORM }); setFormError(null); setShowMoreFields(false); setModalOpen(true); };
  const openEditModal = (product: Product) => { setEditingProduct(product); setForm({ supplier_id: String(product.supplier_id), name: product.name, sku: product.sku ?? "", description: product.description ?? "", current_price: String(product.current_price), currency: product.currency, image_url: product.image_url ?? "", barcode: product.barcode ?? "", category: product.category ?? "", unit: product.unit ?? "", units_per_carton: product.units_per_carton != null ? String(product.units_per_carton) : "", supplier_sku: product.supplier_sku ?? "", current_stock: product.current_stock != null ? String(product.current_stock) : "", min_stock: product.min_stock != null ? String(product.min_stock) : "", recommended_stock: product.recommended_stock != null ? String(product.recommended_stock) : "" }); setFormError(null); setShowMoreFields(false); setModalOpen(true); };
  const startInlineEdit = (product: Product, field: InlineField) => { const value = field === "name" ? product.name : field === "sku" ? product.sku ?? "" : field === "barcode" ? product.barcode ?? "" : field === "category" ? product.category ?? "" : field === "current_price" ? String(product.current_price) : product.current_stock == null ? "" : String(product.current_stock); setInlineEdit({ id: product.id, field, value }); };
  const saveInlineEdit = () => { if (!inlineEdit) return; const value = inlineEdit.value.trim(); if (["name", "sku", "barcode", "category"].includes(inlineEdit.field)) { if (inlineEdit.field === "name" && !value) return; updateProduct.mutate({ [inlineEdit.field]: value || undefined }, { onSuccess: () => setInlineEdit(null) }); return; } const numeric = Number(value); if (!Number.isFinite(numeric) || numeric < 0) return; updateProduct.mutate(inlineEdit.field === "current_price" ? { current_price: numeric } : { current_stock: Math.trunc(numeric) }, { onSuccess: () => setInlineEdit(null) }); };
  const handleSubmit = () => { setFormError(null); if (!form.supplier_id) return setFormError("בחר ספק."); if (!form.name.trim()) return setFormError("שם המוצר הוא שדה חובה."); const price = Number(form.current_price); if (!Number.isFinite(price) || price < 0) return setFormError("הזן מחיר תקין."); if (form.barcode.trim() && !/^\d+$/.test(form.barcode.trim())) return setFormError("ברקוד יכול להכיל ספרות בלבד."); for (const [label, value] of [["יחידות בקרטון", form.units_per_carton], ["מלאי קיים", form.current_stock], ["מלאי מינימום", form.min_stock], ["מלאי מומלץ", form.recommended_stock]] as const) if (value.trim() && (!Number.isFinite(Number(value)) || Number(value) < 0 || !Number.isInteger(Number(value)))) return setFormError(`${label}: יש להזין מספר שלם חיובי.`); const payload = { supplier_id: Number(form.supplier_id), name: form.name.trim(), sku: form.sku.trim() || undefined, description: form.description.trim() || undefined, current_price: price, currency: form.currency, image_url: form.image_url.trim() || undefined, barcode: form.barcode.trim() || undefined, category: form.category.trim() || undefined, unit: form.unit.trim() || undefined, units_per_carton: parseOptionalInt(form.units_per_carton), supplier_sku: form.supplier_sku.trim() || undefined, current_stock: parseOptionalInt(form.current_stock), min_stock: parseOptionalInt(form.min_stock), recommended_stock: parseOptionalInt(form.recommended_stock) }; const onSuccess = () => { setModalOpen(false); setEditingProduct(null); }; if (editingProduct) updateProduct.mutate(payload, { onSuccess }); else createProduct.mutate(payload, { onSuccess }); };
  const renderInlineCell = (product: Product, field: InlineField, display: ReactNode) => { const active = inlineEdit?.id === product.id && inlineEdit.field === field; if (!active) return <button type="button" onClick={() => canManage && startInlineEdit(product, field)} className={canManage ? "group w-full rounded-lg px-1.5 py-1 text-right transition hover:bg-slate-100 dark:hover:bg-slate-800" : "w-full text-right"} title={canManage ? "עריכה ישירה" : undefined}><span>{display}</span>{canManage && <Pencil className="mr-2 inline h-3.5 w-3.5 text-indigo-400 opacity-0 transition group-hover:opacity-100" />}</button>; return <div className="flex items-center gap-1.5"><Input autoFocus value={inlineEdit.value} type={["current_price", "current_stock"].includes(field) ? "number" : "text"} min={["current_price", "current_stock"].includes(field) ? 0 : undefined} step={field === "current_price" ? "0.01" : field === "current_stock" ? "1" : undefined} onChange={(e) => setInlineEdit((current) => current ? { ...current, value: e.target.value } : current)} onKeyDown={(e) => { if (e.key === "Enter") saveInlineEdit(); if (e.key === "Escape") setInlineEdit(null); }} className="h-9 min-w-0" list={field === "category" ? "inline-product-categories" : undefined} /><button type="button" onClick={saveInlineEdit} disabled={updateProduct.isPending} className="rounded-md p-1.5 text-emerald-600 hover:bg-emerald-50" aria-label="שמירה"><Save size={15} /></button><button type="button" onClick={() => setInlineEdit(null)} disabled={updateProduct.isPending} className="rounded-md p-1.5 text-slate-400 hover:bg-slate-100" aria-label="ביטול"><X size={15} /></button></div>; };
  const renderStock = (product: Product, compact = false) => { const percent = stockPercent(product); const tone = stockTone(product); const toneClass = tone === "danger" ? "bg-red-500" : tone === "warning" ? "bg-amber-400" : tone === "healthy" ? "bg-emerald-500" : "bg-slate-300"; return <div className={compact ? "min-w-0" : "min-w-[120px]"}><div className="flex items-center justify-between gap-2 text-sm"><span className={isLowStock(product) ? "font-bold text-red-600" : "font-semibold text-slate-700 dark:text-slate-200"}>{product.current_stock != null ? product.current_stock : "—"}</span>{product.min_stock != null && <span className="text-[11px] text-slate-400">מינ׳ {product.min_stock}</span>}</div>{percent != null && <div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full transition-all ${toneClass}`} style={{ width: `${percent}%` }} /></div>}</div>; };
  const inputClass = "block w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"; const isSaving = createProduct.isPending || updateProduct.isPending;
  return <div className="space-y-6 pb-10">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-3xl font-extrabold tracking-tight text-slate...