"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Ban, Check, ChevronLeft, FileUp, Package, Pencil, RefreshCw, Search, ShieldCheck, ShoppingBag, Trash2, UserRound, Building2, ExternalLink, X } from "lucide-react";
import { adminService, type AdminImport, type AdminOrder, type AdminProduct, type AdminSupplier, type AdminUser } from "@/services/admin-service";

type Tab = "overview" | "users" | "suppliers" | "products" | "orders" | "imports";
const tabs: Array<{ id: Tab; label: string; icon: typeof UserRound }> = [
  { id: "overview", label: "סקירה", icon: ShieldCheck }, { id: "users", label: "משתמשים", icon: UserRound },
  { id: "suppliers", label: "ספקים", icon: Building2 }, { id: "products", label: "מוצרים", icon: Package },
  { id: "orders", label: "הזמנות", icon: ShoppingBag }, { id: "imports", label: "ייבואים", icon: FileUp },
];
const roleLabel = (role: AdminUser["role"]) => role === "admin" ? "מנהל מערכת" : role === "manager" ? "מנהל" : "עובד";
const statusLabel = (status: string) => ({ draft: "טיוטה", submitted: "ממתינה לאישור", approved: "אושרה", sent: "אצל הספק", completed: "הושלמה", cancelled: "בוטלה", FAILED: "נכשלה" } as Record<string, string>)[status] ?? status;

export default function AdminPage() {
  const [tab, setTab] = useState<Tab>("overview");
  const [users, setUsers] = useState<AdminUser[]>([]), [suppliers, setSuppliers] = useState<AdminSupplier[]>([]), [products, setProducts] = useState<AdminProduct[]>([]), [orders, setOrders] = useState<AdminOrder[]>([]), [imports, setImports] = useState<AdminImport[]>([]);
  const [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [error, setError] = useState<string | null>(null), [busy, setBusy] = useState<string | null>(null), [search, setSearch] = useState("");
  const [editUser, setEditUser] = useState<AdminUser | null>(null), [editSupplier, setEditSupplier] = useState<AdminSupplier | null>(null);
  const [userForm, setUserForm] = useState({ full_name: "", email: "", role: "employee" as AdminUser["role"] }), [supplierForm, setSupplierForm] = useState({ name: "" });

  async function load(initial = false) {
    if (initial) setLoading(true); else setRefreshing(true); setError(null);
    try { const [u, s, p, o, i] = await Promise.all([adminService.listUsers(), adminService.listSuppliers(), adminService.listProducts(), adminService.listOrders(), adminService.listImports()]); setUsers(u); setSuppliers(s); setProducts(p); setOrders(o); setImports(i); }
    catch (e: any) { setError(e?.friendlyMessage || e?.response?.data?.message || "לא ניתן לטעון את נתוני מרכז הניהול."); }
    finally { setLoading(false); setRefreshing(false); }
  }
  useEffect(() => { void load(true); }, []);
  async function run(key: string, fn: () => Promise<void>, message: string) { if (!window.confirm(message)) return; setBusy(key); setError(null); try { await fn(); await load(); } catch (e: any) { setError(e?.friendlyMessage || e?.response?.data?.message || "הפעולה נכשלה."); } finally { setBusy(null); } }

  const fu = useMemo(() => filterRows(users, search, u => `${u.full_name} ${u.email} ${roleLabel(u.role)}`), [users, search]);
  const fs = useMemo(() => filterRows(suppliers, search, s => `${s.name} ${s.id}`), [suppliers, search]);
  const fp = useMemo(() => filterRows(products, search, p => `${p.name} ${p.sku ?? ""} ${p.supplier_id}`), [products, search]);
  const fo = useMemo(() => filterRows(orders, search, o => `${o.order_number} ${o.status} ${o.final_total}`), [orders, search]);
  const fi = useMemo(() => filterRows(imports, search, i => `${i.filename} ${i.status} ${i.id}`), [imports, search]);

  return <div dir="rtl" className="space-y-6 pb-12">
    <header className="rounded-3xl border border-slate-200 bg-gradient-to-l from-indigo-50 via-white to-white p-6 shadow-sm dark:border-slate-800 dark:from-indigo-950/30 dark:via-slate-900 dark:to-slate-900">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-600/20"><ShieldCheck size={23}/></div><div><div className="mb-1 text-xs font-extrabold uppercase tracking-[0.16em] text-indigo-600">System Administration</div><h1 className="text-3xl font-black tracking-tight text-slate-950 dark:text-white">מרכז ניהול המערכת</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">ניהול מסודר של משתמשים, ספקים, מוצרים, הזמנות וייבואים — עם פעולות ברורות של עריכה, הפעלה, השבתה ומחיקה.</p></div></div><button type="button" onClick={() => void load()} disabled={refreshing} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700 shadow-sm hover:border-indigo-300 hover:text-indigo-700 disabled:opacity-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200"><RefreshCw size={16} className={refreshing ? "animate-spin" : ""}/> רענון נתונים</button></div>
    </header>
    {error && <div className="flex items-center justify-between gap-4 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-300"><span>{error}</span><button type="button" onClick={() => setError(null)}><X size={17}/></button></div>}
    <nav className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex min-w-max gap-1">{tabs.map(item => { const Icon=item.icon, active=tab===item.id; const count=item.id==="users"?users.length:item.id==="suppliers"?suppliers.length:item.id==="products"?products.length:item.id==="orders"?orders.length:item.id==="imports"?imports.length:null; return <button key={item.id} type="button" onClick={()=>{setTab(item.id);setSearch("");}} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-extrabold transition ${active?"bg-indigo-600 text-white shadow-md":"text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"}`}><Icon size={16}/>{item.label}{count!==null&&<span className={`rounded-full px-1.5 py-0.5 text-[10px] ${active?"bg-white/20":"bg-slate-100 text-slate-500 dark:bg-slate-800"}`}>{count}</span>}</button>})}</div></nav>

    {tab === "overview" ? <Overview users={users} suppliers={suppliers} products={products} orders={orders} imports={imports} loading={loading} onTab={setTab}/> : <section className="space-y-4">
      <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between dark:border-slate-800 dark:bg-slate-900"><div><h2 className="text-lg font-black">{tabs.find(t=>t.id===tab)?.label}</h2><p className="text-xs text-slate-400">הפעולות נמצאות בעמודה הימנית — אין צורך לחפש אותן בתפריטים נסתרים.</p></div><div className="relative w-full sm:w-80"><Search className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="חיפוש..." className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pr-9 pl-3 text-sm outline-none focus:border-indigo-400 dark:border-slate-700 dark:bg-slate-950"/></div></div>
      {tab === "users" && <DataTable headers={["משתמש","תפקיד","סטטוס","פעולות"]} loading={loading} empty="אין משתמשים תואמים">{fu.map(u=><TableRow key={u.id}><Cell><b>{u.full_name}</b><small>{u.email}</small></Cell><Cell>{roleLabel(u.role)}</Cell><Cell><Badge active={u.active}/></Cell><Cell><Actions><ActionButton label="עריכה" icon={Pencil} onClick={()=>{setEditUser(u);setUserForm({full_name:u.full_name,email:u.email,role:u.role});}}/><ActionButton label={u.active?"השבת":"הפעל"} icon={u.active?Ban:Check} tone={u.active?"amber":"green"} disabled={busy===`u${u.id}`} onClick={()=>void run(`u${u.id}`,()=> (u.active?adminService.deactivateUser(u.id):adminService.activateUser(u.id)).then(()=>undefined),u.active?"להשבית את המשתמש?":"להפעיל את המשתמש?")}/><ActionButton label="מחק" icon={Trash2} tone="red" disabled={busy===`ud${u.id}`} onClick={()=>void run(`ud${u.id}`,()=>adminService.deleteUser(u.id),"למחוק את המשתמש לצמיתות? המשתמש חייב להיות מושבת.")}/></Actions></Cell></TableRow>)}</DataTable>}
      {tab === "suppliers" && <DataTable headers={["ספק","מזהה","סטטוס","פעולות"]} loading={loading} empty="אין ספקים תואמים">{fs.map(s=><TableRow key={s.id}><Cell><b>{s.name}</b></Cell><Cell>#{s.id}</Cell><Cell><Badge active={s.active}/></Cell><Cell><Actions><ActionButton label="עריכה" icon={Pencil} onClick={()=>{setEditSupplier(s);setSupplierForm({name:s.name});}}/><ActionButton label={s.active?"השבת":"הפעל"} icon={s.active?Ban:Check} tone={s.active?"amber":"green"} onClick={()=>void run(`s${s.id}`,()=> (s.active?adminService.deactivateSupplier(s.id):adminService.activateSupplier(s.id)).then(()=>undefined),s.active?"להשבית את הספק? גם מוצריו יושבתו.":"להפעיל את הספק?")}/><ActionButton label="מחק" icon={Trash2} tone="red" disabled={busy===`sd${s.id}`} onClick={()=>void run(`sd${s.id}`,()=>adminService.deleteSupplier(s.id),"למחוק את הספק לצמיתות? אם קיימת תלות, השרת יחסום את הפעולה.")}/></Actions></Cell></TableRow>)}</DataTable>}
      {tab === "products" && <DataTable headers={["מוצר","מחיר","ספק","סטטוס","פעולות"]} loading={loading} empty="אין מוצרים תואמים">{fp.map(p=><TableRow key={p.id}><Cell><b>{p.name}</b><small>{p.sku||"ללא מק״ט"}</small></Cell><Cell>{p.current_price.toLocaleString("he-IL")} ₪</Cell><Cell>#{p.supplier_id}</Cell><Cell><Badge active={p.active}/></Cell><Cell><Actions><LinkAction href="/dashboard/catalog" label="פתח בקטלוג"/><ActionButton label="מחק" icon={Trash2} tone="red" disabled={busy===`p${p.id}`} onClick={()=>void run(`p${p.id}`,()=>adminService.deleteProduct(p.id),`למחוק את המוצר "${p.name}" לצמיתות?`)}/></Actions></Cell></TableRow>)}</DataTable>}
      {tab === "orders" && <DataTable headers={["הזמנה","סטטוס","סה״כ","תאריך","פעולות"]} loading={loading} empty="אין הזמנות תואמות">{fo.map(o=><TableRow key={o.id}><Cell><b>{o.order_number}</b></Cell><Cell><StatusBadge status={o.status}/></Cell><Cell>{o.final_total.toLocaleString("he-IL")} ₪</Cell><Cell>{formatDate(o.created_at)}</Cell><Cell><Actions><LinkAction href={`/dashboard/orders/${o.id}`} label="פתח"/><ActionButton label="מחק" icon={Trash2} tone="red" disabled={busy===`o${o.id}`} onClick={()=>void run(`o${o.id}`,()=>adminService.deleteOrder(o.id),`למחוק את ההזמנה ${o.order_number} לצמיתות? פעולה זו אינה הפיכה.`)}/></Actions></Cell></TableRow>)}</DataTable>}
      {tab === "imports" && <DataTable headers={["קובץ","סטטוס","שורות","תאריך","פעולות"]} loading={loading} empty="אין ייבואים תואמים">{fi.map(i=><TableRow key={i.id}><Cell><b>{i.filename}</b><small>#{i.id}</small></Cell><Cell><StatusBadge status={i.status}/></Cell><Cell>{i.row_count??0}</Cell><Cell>{formatDate(i.created_at)}</Cell><Cell>{i.status==="FAILED"?<ActionButton label="מחק" icon={Trash2} tone="red" disabled={busy===`i${i.id}`} onClick={()=>void run(`i${i.id}`,()=>adminService.deleteImport(i.id),"למחוק את הייבוא הכושל ואת קובץ המקור?")}/>:<span className="text-xs font-semibold text-slate-400">היסטוריה נשמרת</span>}</Cell></TableRow>)}</DataTable>}
    </section>}

    {editUser && <Modal title="עריכת משתמש" onClose={()=>setEditUser(null)}><Field label="שם מלא"><input value={userForm.full_name} onChange={e=>setUserForm({...userForm,full_name:e.target.value})}/></Field><Field label="אימייל"><input value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></Field><Field label="תפקיד"><select value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value as AdminUser["role"]})}><option value="employee">עובד</option><option value="manager">מנהל</option><option value="admin">מנהל מערכת</option></select></Field><ModalActions onClose={()=>setEditUser(null)} onSave={()=>void run(`ue${editUser.id}`,async()=>{await adminService.updateUser(editUser.id,userForm);setEditUser(null);},"לשמור את שינויי המשתמש?")}/></Modal>}
    {editSupplier && <Modal title="עריכת ספק" onClose={()=>setEditSupplier(null)}><Field label="שם ספק"><input value={supplierForm.name} onChange={e=>setSupplierForm({name:e.target.value})}/></Field><ModalActions onClose={()=>setEditSupplier(null)} onSave={()=>void run(`se${editSupplier.id}`,async()=>{await adminService.updateSupplier(editSupplier.id,supplierForm);setEditSupplier(null);},"לשמור את שינויי הספק?")}/></Modal>}
  </div>;
}

function Overview({users,suppliers,products,orders,imports,loading,onTab}:{users:AdminUser[];suppliers:AdminSupplier[];products:AdminProduct[];orders:AdminOrder[];imports:AdminImport[];loading:boolean;onTab:(tab:Tab)=>void}) { const cards=[{tab:"users" as Tab,label:"משתמשים",value:users.length,active:users.filter(x=>x.active).length,icon:UserRound},{tab:"suppliers" as Tab,label:"ספקים",value:suppliers.length,active:suppliers.filter(x=>x.active).length,icon:Building2},{tab:"products" as Tab,label:"מוצרים",value:products.length,active:products.filter(x=>x.active).length,icon:Package},{tab:"orders" as Tab,label:"הזמנות",value:orders.length,active:orders.filter(x=>x.status!=="cancelled").length,icon:ShoppingBag},{tab:"imports" as Tab,label:"ייבואים",value:imports.length,active:imports.filter(x=>x.status!=="FAILED").length,icon:FileUp}]; return <section className="space-y-5"><div><h2 className="text-xl font-black">סקירת מערכת</h2><p className="mt-1 text-sm text-slate-500">כל תחום מקבל מסך מסודר עם פעולות ברורות.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(c=><button key={c.tab} type="button" onClick={()=>onTab(c.tab)} className="group rounded-2xl border border-slate-200 bg-white p-5 text-right shadow-sm transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950/50 dark:text-indigo-300"><c.icon size={19}/></span><ChevronLeft size={18} className="text-slate-300"/></div><div className="mt-5 text-3xl font-black">{loading?"—":c.value}</div><div className="mt-1 font-extrabold">{c.label}</div><div className="mt-1 text-xs text-slate-400">{c.active} פעילות</div></button>)}</div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900/50 dark:bg-amber-950/20"><h3 className="font-black text-amber-900 dark:text-amber-200">מחיקה היא פעולה בלתי הפיכה</h3><p className="mt-1 text-sm leading-6 text-amber-800/80 dark:text-amber-300/80">בכל מסך יש כפתור <strong>מחק</strong> גלוי. אם קיימת מגבלת שלמות נתונים, השרת יציג סיבה ברורה במקום למחוק חלקית.</p></div></section>; }
function DataTable({headers,children,loading,empty}:{headers:string[];children:ReactNode;loading:boolean;empty:string}) { return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right"><thead className="border-b border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-950/50"><tr>{headers.map(h=><th key={h} className="px-5 py-3 text-xs font-extrabold text-slate-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{loading?<tr><td colSpan={headers.length} className="p-10 text-center text-sm text-slate-400">טוען נתונים...</td></tr>:children||<tr><td colSpan={headers.length} className="p-10 text-center text-sm font-semibold text-slate-400">{empty}</td></tr>}</tbody></table></div></div>; }
function TableRow({children}:{children:ReactNode}){return <tr className="transition hover:bg-indigo-50/30 dark:hover:bg-slate-800/50">{children}</tr>;} function Cell({children}:{children:ReactNode}){return <td className="px-5 py-4 text-sm text-slate-700 dark:text-slate-200">{children}</td>;} function Actions({children}:{children:ReactNode}){return <div className="flex flex-wrap gap-2">{children}</div>;}
function Badge({active}:{active:boolean}){return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-extrabold ${active?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300":"bg-slate-100 text-slate-500 dark:bg-slate-800"}`}>{active?"פעיל":"מושבת"}</span>;}
function StatusBadge({status}:{status:string}){const good=["approved","completed"].includes(status),bad=["cancelled","FAILED"].includes(status);return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-extrabold ${good?"bg-emerald-50 text-emerald-700":bad?"bg-red-50 text-red-700":"bg-indigo-50 text-indigo-700"}`}>{statusLabel(status)}</span>;}
function ActionButton({label,icon:Icon,tone="neutral",onClick,disabled}:{label:string;icon:typeof Pencil;tone?:"neutral"|"amber"|"green"|"red";onClick:()=>void;disabled?:boolean}){const cls=tone==="red"?"border-red-200 text-red-600 hover:bg-red-50":tone==="amber"?"border-amber-200 text-amber-700 hover:bg-amber-50":tone==="green"?"border-emerald-200 text-emerald-700 hover:bg-emerald-50":"border-slate-200 text-slate-600 hover:bg-slate-50";return <button type="button" disabled={disabled} onClick={onClick} className={`inline-flex h-9 items-center gap-1.5 rounded-lg border bg-white px-3 text-xs font-extrabold transition disabled:opacity-40 dark:bg-slate-900 ${cls}`}><Icon size={14}/>{label}</button>;}
function LinkAction({href,label}:{href:string;label:string}){return <Link href={href} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 text-xs font-extrabold text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300"><ExternalLink size={14}/>{label}</Link>;}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-sm font-bold text-slate-700 dark:text-slate-200"><span className="mb-1.5 block">{label}</span>{children}</label>;}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-black">{title}</h3><button type="button" onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-800"><X size={18}/></button></div><div className="space-y-4 [&_input]:h-10 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-200 [&_input]:bg-white [&_input]:px-3 [&_input]:text-sm [&_select]:h-10 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-slate-200 [&_select]:bg-white [&_select]:px-3 [&_select]:text-sm">{children}</div></div></div>;}
function ModalActions({onClose,onSave}:{onClose:()=>void;onSave:()=>void}){return <div className="flex justify-end gap-2 border-t border-slate-100 pt-4 dark:border-slate-800"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold">ביטול</button><button type="button" onClick={onSave} className="rounded-xl bg-indigo-600 px-5 py-2 text-sm font-bold text-white">שמירה</button></div>;}
function filterRows<T>(rows:T[],query:string,text:(row:T)=>string){const q=query.trim().toLowerCase();return q?rows.filter(r=>text(r).toLowerCase().includes(q)):rows;} function formatDate(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("he-IL",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d);}
