"""Minimal additive production schema bootstrap.

Alembic remains the canonical migration mechanism. This startup fallback exists
for Render services where the Blueprint pre-deploy command is not attached or
was skipped. All changes are additive and idempotent.
"""
from __future__ import annotations

import os

from sqlalchemy import create_engine, inspect, text


def _database_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is required for production schema bootstrap")
    if url.startswith("postgres://"):
        return "postgresql+psycopg2://" + url[len("postgres://") :]
    if url.startswith("postgresql://"):
        return "postgresql+psycopg2://" + url[len("postgresql://") :]
    return url


def _add_columns(conn, table: str, definitions: dict[str, str]) -> None:
    inspector = inspect(conn)
    existing = {c["name"] for c in inspector.get_columns(table)}
    for name, definition in definitions.items():
        if name not in existing:
            conn.execute(text(f'ALTER TABLE "{table}" ADD COLUMN "{name}" {definition}'))


def ensure_schema() -> None:
    engine = create_engine(_database_url(), pool_pre_ping=True)
    try:
        with engine.begin() as conn:
            conn.execute(text("SELECT pg_advisory_xact_lock(73184219)"))
            inspector = inspect(conn)
            tables = set(inspector.get_table_names())

            if "products" not in tables:
                raise RuntimeError("products table does not exist; run Alembic migrations first")

            _add_columns(
                conn,
                "products",
                {
                    "category_source": "VARCHAR(30)",
                    "category_confidence": "NUMERIC(5,4)",
                    "category_reviewed": "BOOLEAN NOT NULL DEFAULT FALSE",
                },
            )

            if "suppliers" in tables:
                _add_columns(conn, "suppliers", {"ordering_rules": "JSON"})
            if "orders" in tables:
                _add_columns(
                    conn,
                    "orders",
                    {
                        "reminder_state": "VARCHAR(20)",
                        "reminder_rules_snapshot": "JSON",
                        "next_reminder_at": "TIMESTAMP",
                    },
                )
                indexes = {i["name"] for i in inspect(conn).get_indexes("orders")}
                if "ix_orders_next_reminder_at" not in indexes:
                    conn.execute(
                        text(
                            'CREATE INDEX "ix_orders_next_reminder_at" '
                            'ON "orders" ("next_reminder_at")'
                        )
                    )

            if "product_classification_feedback" not in tables:
                conn.execute(
                    text(
                        """
                        CREATE TABLE product_classification_feedback (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            tenant_id INTEGER NOT NULL REFERENCES tenants(id),
                            product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
                            normalized_name VARCHAR(255) NOT NULL,
                            predicted_category VARCHAR(100),
                            actual_category VARCHAR(100) NOT NULL,
                            source VARCHAR(30) NOT NULL DEFAULT 'USER',
                            confidence NUMERIC(5,4),
                            created_by INTEGER REFERENCES users(id),
                            created_at TIMESTAMP NOT NULL
                        )
                        """
                    )
                )

            indexes = {i["name"] for i in inspect(conn).get_indexes("product_classification_feedback")}
            index_specs = {
                "ix_product_classification_feedback_tenant_id": ["tenant_id"],
                "ix_product_classification_feedback_product_id": ["product_id"],
                "ix_product_classification_feedback_normalized_name": ["normalized_name"],
            }
            for index_name, columns in index_specs.items():
                if index_name not in indexes:
                    quoted = ", ".join(f'"{column}"' for column in columns)
                    conn.execute(
                        text(
                            f'CREATE INDEX "{index_name}" '
                            f'ON product_classification_feedback ({quoted})'
                        )
                    )
    finally:
        engine.dispose()


if __name__ == "__main__":
    ensure_schema()
    print("Production schema bootstrap completed")
