"""Minimal production schema bootstrap for Render startup.

This is intentionally limited to additive, idempotent changes required by the
current Product ORM. It is a safety net for existing Render services where
Alembic cannot be guaranteed to run before Gunicorn starts.

Alembic remains the canonical migration mechanism; this bootstrap only repairs
the known product-classification schema drift and never deletes or rewrites
existing data.
"""
from __future__ import annotations

import os

from sqlalchemy import create_engine, inspect, text


PRODUCT_COLUMNS = {
    "category_source": "VARCHAR(30)",
    "category_confidence": "NUMERIC(5,4)",
    "category_reviewed": "BOOLEAN NOT NULL DEFAULT FALSE",
}


def _database_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is required for production schema bootstrap")
    if url.startswith("postgres://"):
        url = "postgresql+psycopg2://" + url[len("postgres://") :]
    elif url.startswith("postgresql://"):
        url = "postgresql+psycopg2://" + url[len("postgresql://") :]
    return url


def ensure_schema() -> None:
    engine = create_engine(_database_url(), pool_pre_ping=True)
    try:
        with engine.begin() as conn:
            # Serialize startup repairs across Gunicorn workers/instances.
            conn.execute(text("SELECT pg_advisory_xact_lock(73184219)"))
            inspector = inspect(conn)
            tables = set(inspector.get_table_names())
            if "products" not in tables:
                raise RuntimeError("products table does not exist; run Alembic migrations first")

            columns = {c["name"] for c in inspector.get_columns("products")}
            for name, definition in PRODUCT_COLUMNS.items():
                if name not in columns:
                    conn.execute(text(f'ALTER TABLE products ADD COLUMN "{name}" {definition}'))

            # The feedback table is additive and is needed by the classification
            # learning workflow. Create it only when absent.
            if "product_classification_feedback" not in tables:
                conn.execute(
                    text(
                        """
                        CREATE TABLE product_classification_feedback (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            tenant_id INTEGER NOT NULL REFERENCES tenants(id),
                            product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
                            normalized_name VARCHAR(255) NOT NULL,
                            predicted_category VARCHAR(100),
                            actual_category VARCHAR(100) NOT NULL,
                            source VARCHAR(30) NOT NULL DEFAULT 'USER',
                            confidence NUMERIC(5,4),
                            created_by INTEGER REFERENCES users(id),
                            created_at TIMESTAMP NOT NULL
                        )
                        """
                    )
                )

            indexes = {i["name"] for i in inspect(conn).get_indexes("product_classification_feedback")}
            index_specs = {
                "ix_product_classification_feedback_tenant_id": ["tenant_id"],
                "ix_product_classification_feedback_product_id": ["product_id"],
                "ix_product_classification_feedback_normalized_name": ["normalized_name"],
            }
            for index_name, columns_for_index in index_specs.items():
                if index_name not in indexes:
                    quoted = ", ".join(f'"{c}"' for c in columns_for_index)
                    conn.execute(
                        text(
                            f'CREATE INDEX "{index_name}" '
                            f'ON product_classification_feedback ({quoted})'
                        )
                    )
    finally:
        engine.dispose()


if __name__ == "__main__":
    ensure_schema()
    print("Production schema bootstrap completed")
