from datetime import datetime, timezone
import re

from app.extensions import db


class Product(db.Model):
    __tablename__ = "products"
    __table_args__ = (
        db.Index(
            "uq_products_tenant_sku",
            "tenant_id",
            "sku",
            unique=True,
            postgresql_where=db.text("sku IS NOT NULL AND btrim(sku) <> ''"),
            sqlite_where=db.text("sku IS NOT NULL AND trim(sku) <> ''"),
        ),
        db.Index(
            "uq_products_tenant_barcode",
            "tenant_id",
            "barcode",
            unique=True,
            postgresql_where=db.text("barcode IS NOT NULL AND btrim(barcode) <> ''"),
            sqlite_where=db.text("barcode IS NOT NULL AND trim(barcode) <> ''"),
        ),
    )

    id = db.Column(db.Integer, primary_key=True)
    tenant_id = db.Column(db.Integer, db.ForeignKey("tenants.id"), nullable=False, index=True)
    supplier_id = db.Column(db.Integer, db.ForeignKey("suppliers.id"), nullable=False, index=True)
    sku = db.Column(db.String(100), index=True)
    name = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    current_price = db.Column(db.Numeric(12, 2), default=0.0, nullable=False)
    currency = db.Column(db.String(3), default="ILS", nullable=False)
    active = db.Column(db.Boolean, default=True, nullable=False)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    image_url = db.Column(db.String(500), nullable=True)
    barcode = db.Column(db.String(64), nullable=True, index=True)
    category = db.Column(db.String(100), nullable=True, index=True)
    category_source = db.Column(db.String(30), nullable=True)
    category_confidence = db.Column(db.Numeric(5, 4), nullable=True)
    category_reviewed = db.Column(db.Boolean, nullable=False, default=False)
    unit = db.Column(db.String(50), nullable=True)
    units_per_carton = db.Column(db.Integer, nullable=True)
    supplier_sku = db.Column(db.String(100), nullable=True)
    current_stock = db.Column(db.Integer, nullable=True)
    min_stock = db.Column(db.Integer, nullable=True)
    recommended_stock = db.Column(db.Integer, nullable=True)

    supplier = db.relationship("Supplier", back_populates="products")
    supplier_offers = db.relationship(
        "SupplierProductOffer", back_populates="product", cascade="all, delete-orphan"
    )
    classification_feedback = db.relationship(
        "ProductClassificationFeedback", back_populates="product", cascade="all, delete-orphan"
    )

    @staticmethod
    def is_synthetic_barcode(value):
        """Return True for barcodes generated by the legacy catalog importer."""
        normalized = str(value or "").strip()
        return bool(re.fullmatch(r"990000010000\d+", normalized))

    def data_quality(self):
        """Expose non-destructive catalog quality diagnostics to the UI/API."""
        missing_fields = []
        if self.current_price is None or float(self.current_price) <= 0:
            missing_fields.append("price")
        if not str(self.category or "").strip():
            missing_fields.append("category")
        if not str(self.unit or "").strip():
            missing_fields.append("unit")
        if not str(self.sku or "").strip() and not str(self.supplier_sku or "").strip():
            missing_fields.append("sku")
        if not str(self.barcode or "").strip():
            missing_fields.append("barcode")

        warnings = []
        barcode_kind = "missing"
        if self.is_synthetic_barcode(self.barcode):
            barcode_kind = "synthetic"
            warnings.append("synthetic_barcode")
        elif str(self.barcode or "").strip():
            barcode_kind = "supplier"
        if self.current_price is not None and float(self.current_price) <= 0:
            warnings.append("missing_price")

        return {
            "needs_review": bool(missing_fields or warnings),
            "missing_fields": missing_fields,
            "warnings": warnings,
            "barcode_kind": barcode_kind,
        }
    def to_dict(self):
        # Keep the catalog's original unit value intact for imports and supplier
        # data. Inventory has a separate normalized stock unit: cartons by
        # default, or pieces only when the product explicitly uses "יחידה".
        stock_unit = "יחידה" if str(self.unit or "").strip() == "יחידה" else "ארגז"
        return {
            "id": self.id,
            "supplier_id": self.supplier_id,
            "sku": self.sku,
            "name": self.name,
            "description": self.description,
            "current_price": float(self.current_price) if self.current_price is not None else None,
            "currency": self.currency,
            "active": self.active,
            "created_at": self.created_at.isoformat(),
            "image_url": self.image_url,
            "barcode": self.barcode,
            "category": self.category,
            "category_source": self.category_source,
            "category_confidence": float(self.category_confidence) if self.category_confidence is not None else None,
            "category_reviewed": self.category_reviewed,
            "unit": self.unit,
            "stock_unit": stock_unit,
            "units_per_carton": self.units_per_carton,
            "supplier_sku": self.supplier_sku,
            "current_stock": self.current_stock,
            "min_stock": self.min_stock,
            "recommended_stock": self.recommended_stock,
            "data_quality": self.data_quality(),
        }
